### ISSUE TITLE
Getting a value error when calculating support and resistance

### ISSUE THREAD

**Issue by pranavlal** [GregoryMorse/trendln#22]
Hi,

I am trying to calculate support and resistance levels  for a set of closing prices. These are in a pandas data frame. When I run my code, I get the following error.

Traceback (most recent call last):
  File "speak_candle_pattern.py", line 112, in <module>
    sr_frame=calculate_support_resistance(ema_frame)
  File "speak_candle_pattern.py", line 95, in calculate_support_resistance
    minvals, maxvals = trendln.calc_support_resistance(df['close'],accuracy=1)
  File "/home/pranav/.virtualenvs/stocks/lib/python3.7/site-packages/trendln/__init__.py", line 737, in calc_support_res
istance
    extremaIdxs = get_extrema(h, extmethod, accuracy)
  File "/home/pranav/.virtualenvs/stocks/lib/python3.7/site-packages/trendln/__init__.py", line 456, in get_extrema
    minFunc, maxFunc, numdiff_extrema = get_minmax(h)
  File "/home/pranav/.virtualenvs/stocks/lib/python3.7/site-packages/trendln/__init__.py", line 442, in get_minmax
    mom, momacc = d_dx(clarr), d2_dx2(clarr)
  File "/home/pranav/.virtualenvs/stocks/lib/python3.7/site-packages/findiff/operators.py", line 79, in __call__
    return self.apply(rhs, *args, **kwargs)
  File "/home/pranav/.virtualenvs/stocks/lib/python3.7/site-packages/findiff/operators.py", line 94, in apply
    return self.pds(rhs, *args, **kwargs)
  File "/home/pranav/.virtualenvs/stocks/lib/python3.7/site-packages/findiff/diff.py", line 216, in __call__
    return self.apply(rhs, *args, **kwargs)
  File "/home/pranav/.virtualenvs/stocks/lib/python3.7/site-packages/findiff/diff.py", line 275, in apply
    return self.diff(u, h, acc)
  File "/home/pranav/.virtualenvs/stocks/lib/python3.7/site-packages/findiff/diff.py", line 287, in diff
    coefs = coefficients(self.order, acc)
  File "/home/pranav/.virtualenvs/stocks/lib/python3.7/site-packages/findiff/coefs.py", line 32, in coefficients
    _validate_acc(acc)
  File "/home/pranav/.virtualenvs/stocks/lib/python3.7/site-packages/findiff/coefs.py", line 207, in _validate_acc
    raise ValueError('Accuracy order acc must be positive EVEN integer')
ValueError: Accuracy order acc must be positive EVEN integer

I am unable to determine what I am doing wrong. My complete code is below.

def calculate_support_resistance(df):
	minvals, maxvals = trendln.calc_support_resistance(df['close'],accuracy=1)
	df["Resistance"]=maxvals
	df['Support']=minvals
	return df

[Quote-Equity-HDFCBANK-EQ-05-01-2020-to-05-01-2021.txt](https://github.com/GregoryMorse/trendln/files/5931513/Quote-Equity-HDFCBANK-EQ-05-01-2020-to-05-01-2021.txt)

I am attaching a csv file that contains the data I am using.

**Comment by pranavlal** [comment]
Hi all,
I solved this problem. I had to specify an accuracy containing an even number so a value of 2 did the job.

**Comment by pranavlal** [comment]
I am closing the issue since all I had to do was to specify an accuracy value of 2 since the parameter needed an even umber
